[include]
paths = ["/etc/ublue-os/topgrade.toml"]

[misc]
no_self_update = true
disable = ["toolbx", "self_update"]
ignore_failures = ["distrobox", "flatpak", "brew_cask", "brew_formula", "nix", "pip3"]

[linux]
rpm_ostree = true
