[include]
paths = ["/etc/ublue-os/topgrade.toml"]

[misc]
no_self_update = true
disable = ["toolbx", "self_update"]
ignore_failures = ["distrobox", "flatpak", "brew_cask", "brew_formula", "nix", "pip3", "helm", "home_manager", "firmware"]
assume_yes = true
no_retry = false

[linux]
rpm_ostree = true
