name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          use_username: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
